name: ST-WarpReloaded
main: net.starly.warp.WarpMain
author: Starly Team
website: http://starly.kr/

description: BoilerPlate Plugin

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:
  워프:
    description: Warp Plugin Command

permissions:
  warp.teleport:
    description: 워프 이동
  warp.forcedteleport:
    description: 다른 플레이어를 워프
  warp.create:
    description: 워프 생성
  warp.delete:
    description: 워프 삭제
  warp.spawn:
    description: 스폰 이동
  warp.list:
    description: 워프 목록
  warp.commandCreate:
    description: 명령어 등록
  warp.commandDelete:
    description: 명령어 삭제
  warp.*:
    description: permission of ST-WarpReloaded plugin.
    children:
      - warp.teleport
      - warp.forcedteleport
      - warp.create
      - warp.delete
      - warp.spawn
      - warp.list
      - warp.commandCreate
      - warp.commandDelete