name: ST-WarpReloaded
main: net.starly.warp.WarpMain
author: Starly Team
website: http://starly.kr/

description: BoilerPlate Plugin

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:
  워프:
    description: Warp Plugin Command