name: ST-WarpReloaded
main: net.starly.warp.WarpMain
author: Starly Team
website: http://starly.kr/

description: BoilerPlate Plugin

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:
  워프:
    description: Warp Plugin Command

permissions:
  starly.warp.teleport:
    description: 워프 이동
    default: op
  starly.warp.forcedteleport:
    description: 다른 플레이어를 워프
    default: op
  starly.warp.create:
    description: 워프 생성
    default: op
  starly.warp.delete:
    description: 워프 삭제
    default: op
  starly.warp.list:
    description: 워프 목록
    default: op
  starly.warp.triggerCreate:
    description: 트리거 등록
    default: op
  starly.warp.triggerDelete:
    description: 트리거 삭제
    default: op
  starly.warp.reload:
    description: 플러그인 리로드
    default: op
  starly.warp.*:
    description: permission of ST-WarpReloaded plugin.
    children:
      - starly.warp.teleport
      - starly.warp.forcedteleport
      - starly.warp.create
      - starly.warp.delete
      - starly.warp.list
      - starly.warp.triggerCreate
      - starly.warp.triggerDelete
      - starly.warp.reload