package net.starly.warp.enums;

public enum MessageType {
    WARP_COMPLETE, WARP_DELETE_COMPLETE, WARP_CREATE_COMPLETE, PERMISSION_DENIED, NO_EXIST_WARP_DELETE, NO_EXIST_WARP_MOVE,
    EXIST_WARP_NAME, WRONG_PLATFORM, UNREGISTER_SPAWN, REGISTER_SPAWN, NO_EXIST_SPAWN_MOVE, NO_EXIST_SPAWN_DELETE, EMPTY_WARP_LIST,
    WARP_LIST_TITLE, WARP_LIST_FORMAT, NO_EXIST_PLAYER_WARP, FORCE_TELEPORTED, EXIST_COMMAND, NO_EXIST_COMMAND, NO_EXIST_WARP_REGISTER_COMMAND,
    COMMAND_CREATE_SUCCESS, COMMAND_DELETE_SUCCESS
}
