package net.starly.warp.enums;

public enum MessageType {
    WARP_COMPLETE, WARP_DELETE_COMPLETE, WARP_CREATE_COMPLETE, PERMISSION_DENIED, NO_EXIST_WARP_DELETE, NO_EXIST_WARP_MOVE,
    EXIST_WARP_NAME, WRONG_PLATFORM, UNREGISTER_SPAWN, REGISTER_SPAWN, NO_EXIST_SPAWN_MOVE, NO_EXIST_SPAWN_DELETE, EMPTY_WARP_LIST
}
